### ISSUE TITLE
Fails to compile on OSX 10.9

### ISSUE THREAD

**Issue by jasonm23** [rjpower/lua-checker#1]
```
make
bison --defines=lua_parser.h lua.y -o lua_parser.cc
g++ -c -Wall -g -Ilua/src -MMD lua_simplifier.cc
lua_simplifier.cc:47:3: error: use of undeclared identifier 'exit'
  exit(1);
  ^
1 error generated.
make: *** [lua_simplifier.o] Error 1
```

**Comment by rjpower** [comment]
Fixed with #2 .  Updated readme to indicate this is cloned from Google Code.
